# Generated by Django 3.2.16 on 2022-10-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deb', '0019_immutable_metadata_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='release',
            name='label',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='release',
            name='origin',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='release',
            name='version',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='releasefile',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='releasefile',
            name='label',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='releasefile',
            name='origin',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='releasefile',
            name='version',
            field=models.TextField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='release',
            unique_together={('codename', 'suite', 'distribution', 'version', 'origin', 'label', 'description')},
        ),
        migrations.AlterUniqueTogether(
            name='releasefile',
            unique_together={('codename', 'suite', 'distribution', 'origin', 'label', 'components', 'architectures', 'relative_path', 'sha256', 'artifact_set_sha256')},
        ),
    ]
