# Generated by Django 3.2.16 on 2022-11-28 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("deb", "0020_add_release_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="aptrepository",
            name="signing_service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deb_aptrepository",
                to="deb.aptreleasesigningservice",
            ),
        ),
        migrations.AddField(
            model_name="release",
            name="signing_service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deb_release",
                to="deb.aptreleasesigningservice",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="release",
            unique_together={
                (
                    "codename",
                    "suite",
                    "distribution",
                    "version",
                    "origin",
                    "label",
                    "description",
                    "signing_service",
                )
            },
        ),
    ]
