# Generated by Django 3.2.16 on 2022-12-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deb', '0021_add_default_signing_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='aptrepository',
            name='signing_service_release_overrides',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterUniqueTogether(
            name='release',
            unique_together={('codename', 'suite', 'distribution', 'version', 'origin', 'label', 'description')},
        ),
        migrations.RemoveField(
            model_name='release',
            name='signing_service',
        ),
    ]
